### ISSUE TITLE
Open3D Input Keys Error when using iPhone 3D Scanner Data

### ISSUE THREAD

**Issue by JyotiLuxolis** [likojack/bnv_fusion#16]
Hello, I am trying to use iphone 3D Scanner Data to reconstruct a model. However, when I execute `run_e3e.py` I get the following error:
```
Error executing job with overrides: ['model=fusion_pointnet_model', 'dataset=fusion_inference_dataset_arkit', 'trainer.checkpoint=/Data/pretrained/pointnet_tcnn.ckpt', 'dataset.scan_id=iphone', 'dataset.data_dir=/Data/data/', 'model.tcnn_config=/Data/src/models/tcnn_config.json']
Traceback (most recent call last):
  File "/Data/src/run_e2e.py", line 281, in main
    neural_map.volume.to_tensor()
  File "/Data/src/models/sparse_volume.py", line 550, in to_tensor
    buf_indices, masks = self.tensor_indexer.insert(active_keys, indexer_value)
RuntimeError: [Open3D Error] (void open3d::core::HashMap::CheckKeyValueLengthCompatibility(const open3d::core::Tensor&, const std::vector<open3d::core::Tensor>&) const) /root/Open3D/cpp/open3d/core/hashmap/HashMap.cpp:388: Input number of keys should > 0, but got 0.
```

Any guidance on how I can fix this will be appreciated.

**Comment by likojack** [comment]
Looks like the length of values you like to insert is zero. Can you check if you have valid depth values in your depth maps?

**Comment by JyotiLuxolis** [comment]
Thanks a lot for the feedback. You were right. I was using the "Lidar Adcanced" mode with the 3D Scanner App and it wasn't saving depth maps. I switched to the normal "Lidar" mode and now it works fine.
